security:
    encoders:
        AM\AdminBundle\Entity\Administrator: sha512
        AM\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        admin_users:
            entity: { class: AM\AdminBundle\Entity\Administrator, property: username }
        users:
            entity: { class: AM\UserBundle\Entity\User, property: username }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern: ^/admin
            anonymous: true
            provider: admin_users
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: admin_index
            logout:
                path: admin_logout
                target: admin_login
                #invalidate_session: false

        user_area:
            pattern: ^/
            anonymous: true
            provider: users
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: site_home
            logout:
                path: user_logout
                target: user_login

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/new$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/create$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, roles: ROLE_USER }
        - { path: ^/mymusics, roles: ROLE_USER }
